Vagrant.configure("2") do |config|
  config.vm.box = "peru/ubuntu-18.04-desktop-amd64"
  config.vm.box_version = "20210701.01"
  config.vm.provision "file", source: "../../../", destination: "$HOME/uocli"
end
